WORK_DIR: None # */exp_000
ROOT: None # */src
exp_name: None # work dir name

debug: False
train_flag: True
infer_flag: True
log_flag: True

mlflow: True
calc_test_score: True

###############################

num_workers: 2
device: cuda
early_stopping_steps: 1000
verbose: 1