tr_transforms:
  - Normalize
  - ToTensorV2

tr_transform_params:
  color_mean: [0.485, 0.456, 0.406]
  color_std: [0.229, 0.224, 0.225]

val_transforms:
  - Normalize
  - ToTensorV2

val_transform_params:
  color_mean: [0.485, 0.456, 0.406]
  color_std: [0.229, 0.224, 0.225]
